version: '3.8'

services:
  identity-service:
    image: rish0912/movieapp-identity:latest
    container_name: identity-service
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=my_postgres;Port=5432;Database=IdentityDb;Username=postgres;Password=postgres;
      - Otlp__Endpoint=http://otel-collector:4317
      - Cors__AllowedOrigins=http://${EC2_HOST:-localhost}:3000
    ports:
      - "5001:8080"
    networks:
      - movieapp-network

  movie-service:
    image: rish0912/movieapp-movie:latest
    container_name: movie-service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=my_postgres;Port=5432;Database=MovieDb;Username=postgres;Password=postgres;
      - Otlp__Endpoint=http://otel-collector:4317
      - RabbitMq__Host=rabbitmq://rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - Cors__AllowedOrigins=http://${EC2_HOST:-localhost}:3000
    ports:
      - "5002:8080"
    networks:
      - movieapp-network
  
  rating-service:
    image: rish0912/movieapp-rating:latest
    container_name: rating-service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=my_postgres;Port=5432;Database=RatingDb;Username=postgres;Password=postgres;
      - Otlp__Endpoint=http://otel-collector:4317
      - JwtSettings__SecretKey=SecretForMovieAppRequiredToCreateJwt
      - JwtSettings__Issuer=movieApp
      - JwtSettings__Audience=movieApp-clients
      - RabbitMq__Host=rabbitmq://rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - Services__MovieService__BaseUrl=http://movie-service:8080
      - Cors__AllowedOrigins=http://${EC2_HOST:-localhost}:3000
    ports:
      - "5003:8080"
    networks:
      - movieapp-network
  
  frontend:
    image: rish0912/movieapp-frontend:latest
    container_name: web-app
    ports:
      - "3000:3000"
    networks:
      - movieapp-network
    depends_on:
      - identity-service
      - movie-service
      - rating-service

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - movieapp-network

networks:
  movieapp-network:
    driver: bridge

